### ISSUE TITLE
Use HTTPS for Oracle tutorial links in Wiki

### ISSUE THREAD

**Issue by lol768** [chatterbox-works/Chatterbox#13]
I'd do it myself but I can't.

**Comment by gdude2002** [comment]
This is the most nitpickiest ticket I've seen. 

Let's do it!

**Comment by jkcclemens** [comment]
Fixed.

**Comment by lol768** [comment]
Please reopen: Fix is not appropriate.

https://github.com/chatterbox-works/Chatterbox/wiki/Writing-a-hook

**Comment by gdude2002** [comment]
Reopened: Fix is not appropriate

**Comment by lol768** [comment]
Thanks

**Comment by jkcclemens** [comment]
I hate all of you. Thanks for at least showing me where it was this time, @lol768. Fixed.
