### ISSUE TITLE
Blatant act of US imperialism manifest through locale strings

### ISSUE THREAD

**Issue by korikisulda** [chatterbox-works/Chatterbox#15]
Comrades, I must protest the imperialism inherent in giving only the US imperialist en_US locale the fully qualified locale name. Clearly, this is an act of blatant US aggression against Spain, France, and Japan.

**Comment by gdude2002** [comment]
What are the actual qualified names supposed to be?

**Comment by jkcclemens** [comment]
I don't know the dialects for the other ones. I wrote the Spanish...

**Comment by korikisulda** [comment]
es_ES, fr_FR, ja_JP
