### ISSUE TITLE
Default configuration does not operate as expected

### ISSUE THREAD

**Issue by turt2live** [chatterbox-works/Chatterbox#21]
Steps to reproduce:
1) On a clean server, install Chatterbox (built from current master at 3c4bfe6720eac3d24c51db6a3a339cba578f6c53)
2) Start the server
3) Login to the server and send a message
4) You should receive something similar to the following
![image](https://cloud.githubusercontent.com/assets/1190097/7904619/227a6db0-07c0-11e5-9e18-4a6e92ec91bf.png)

**Comment by jkcclemens** [comment]
Any errors in the log?

**Comment by turt2live** [comment]
Nothing obvious.
Full server log: [link](http://i.turt2live.com/RNjE.txt)

Note: server is in offline mode for testing purposes.

**Comment by jkcclemens** [comment]
It should be the default, but can I see the config?

**Comment by turt2live** [comment]
[Configuration](http://i.turt2live.com/HV9e.txt) (unmodified)

**Comment by turt2live** [comment]
Resolved the issue in part with the help of @jkcclemens by adding `[@(channel.getTag())]` to the format. This ticket should still be addressed more correctly though.

Noting this for anyone that needs a temporary fix :)

**Comment by jkcclemens** [comment]
I don't know why, but the start and end matchers aren't finding the JSON signifier when it's at the beginning of the format.

**Comment by jkcclemens** [comment]
This is actually the devil.
